### ISSUE TITLE
The example bootstrap config doesn't work

### ISSUE THREAD

**Issue by cameronbrunner** [UnivaCorporation/tortuga-kit-azureadapter#25]
The example bootstrap config file references the now removed `identify-node` endpoint:

Changes in tortuga here:

https://github.com/UnivaCorporation/tortuga/commit/19ec8e7801c2da26906f59e947b707ea2d8e835c

Bootstrap here:

https://github.com/UnivaCorporation/tortuga-kit-azureadapter/blob/master/tortuga_kits/azureadapter_6_3_0/files/ubuntu_bootstrap.py.tmpl#L99

**Comment by EmmEff** [comment]
Resolved by:

https://github.com/UnivaCorporation/tortuga/pull/146
